import mongoose from 'mongoose'
const Schema = mongoose.Schema;

// _id autogenerated by mongodb
const CarSchema = new Schema({
    name: String
});

const Car = mongoose.model('cars', CarSchema);

export default Car;